### PR TITLE
Add a note - YAML truncates trailing floating point zeroes

### PR DESCRIPTION
**Pull request by Saransh-cpp**
<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to respond to your contribution.
To ensure that the right people get notified, you can tag some of the last contributors with `@githubname`.

Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum. If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact the HSF training convenors ([contacts here](https://hepsoftwarefoundation.org/workinggroups/training.html)).

You may delete these instructions from your pull request.

\- HSF Training
</details>

This might need a few tweaks (based on suggestions), given that the text looks a bit long right now.

### CODE REVIEW

**Review by klieret — APPROVED** [review]
Thanks! This might also be relevant for the gitlab version of this training

**Comment by klieret** [comment]
@all-contributors please add @Saransh-cpp for content

**Comment by Saransh-cpp** [comment]
Thanks for the review!

> This might also be relevant for the gitlab version of this training

I am not very familiar with GitLab CI, but I am guessing this will go somewhere on this page - https://hsf-training.github.io/hsf-training-cicd/08-eins-zwei-dry/index.html?

**Comment by klieret** [comment]
I also don't see it coming up in one of the episodes itself, but it could be added (with a little bit more context) on the yaml page: https://hsf-training.github.io/hsf-training-cicd/03-understanding-yaml/index.html

**Comment by klieret** [comment]
What do you think @wdconinc ?

**Comment by wdconinc** [comment]
I'd put a callout box after https://hsf-training.github.io/hsf-training-cicd/03-understanding-yaml/index.html#scalars when you introduced scalars and point out that versions are best stored as strings.

I don't see it fit in the eins zwei DRY because that one focuses on extends to scale up, not on parallel matrix.

**Comment by wdconinc** [comment]
That's in contrast to https://hsf-training.github.io/hsf-training-cicd-github/09-the-matrix/index.html where it would fit when the first matrix is used at https://hsf-training.github.io/hsf-training-cicd-github/09-the-matrix/index.html#building-a-matrix-across-different-versions (though the three component + suffix version number 6.26.10-conda doesn't lead to confusion).

**Pull request merged**
